name: JoinUI
main: JoinUI\Main
version: 1.0.0
api: 5.0.0
author: ZyberPE
depend:
  - FormAPI

commands:
  howtooplay:
    description: Open the How To Play guide
    usage: "/howtooplay"
    permission: joinui.use

permissions:
  joinui.use:
    default: true
